### ISSUE TITLE
Sync patient data from user to server

### ISSUE THREAD

**Issue by dvenkatr** [resolvetosavelives/redapp-server#2]
As a nurse, I want the patient records on device to be sent in batches to the backend, so that the central database is updated, and the data is safe.

### Patient data model
ID - UUID [to discuss]
Full Name - String
Age when created - Integer
Date of Birth - Date
Gender (male / female / transgender) - Enum/String
Status (active, dead, migrated, unresponsive, other [define other]) - Enum/String

### Address data model
id – uuid
street address - string
colony - string
village - string
district - string
state - string
country - string
pin - string

### Phone number data model
number - string
type -string
active - boolean

### Relationships
Patient belongs to an address
Patient has and belongs to many phone numbers

**Comment by govindkrjoshi** [comment]
Questions:

- Why are UUIDs needed?
- What is the "other" patient status?
- What should the status be when a patient is "Removed from call list"?
- Should village/colony be the same field? Should they be mandatory?
- Should we perform any validation on the mobile number?

**Comment by ssrihari** [comment]
> - What is the "other" patient status?
> - What should the status be when a patient is "Removed from call list"?

Not relevant for MVP.

>  - Should we perform any validation on the mobile number?

No, as discussed with Daniel. To allow landlines, extensions, etc.

> - Should village/colony be the same field? Should they be mandatory?

Needs answers.
